# .github/workflows/deploy.yml
name: Terraform EC2 + Docker via Ansible

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action'
        required: true
        default: 'create'
        type: choice
        options:
          - create
          - destroy

jobs:
  Terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform  Apply or Destroy
        working-directory: terraform
        run: |
          if [ "${{ github.event.inputs.action }}" = "create" ]; then
            terraform apply -auto-approve
          else
            terraform destroy -auto-approve
          fi
      - name: Copy IP file to root (optional)
        working-directory: terraform
        run: cp ip.txt ../ip.txt

      - name: Get EC2 IP
        id: ec2ip
        working-directory: terraform
        run: echo "ip=$(cat ip.txt)" >> $GITHUB_OUTPUT

      - name: Debug IP file
        working-directory: terraform
        run: cat ip.txt

      - name: Debug EC2 IP output
        run: |
          ip="${{ steps.ec2ip.outputs.ip }}"
          echo "Fetched EC2 IP: $ip"


      - name: Install Ansible & SSH tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Install Docker Ansible Role
        run: ansible-galaxy install bsmeding.docker

      - name: Save EC2 Private Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Create Ansible Inventory
        run: |
          echo "[all]" > inventory.ini
          echo "${{ steps.ec2ip.outputs.ip }} ansible_user=ec2-user ansible_ssh_private_key_file=key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory.ini

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini ansible/docker_installation.yml
